### ISSUE TITLE
crates.io?

### ISSUE THREAD

**Issue by mathstuf** [jojonv/rust-win32error#5]
Seems this isn't on crates.io. Is that intended? If so, could a stanza be added to the example `Cargo.toml` snippet in the Readme? Also, a tag for 0.8.0 would be great.

Thanks.

**Comment by jojonv** [comment]
Hi, it's on crates.io but wrongly named see [rust_win32error](https://crates.io/crates/rust_win32error).

**Comment by mathstuf** [comment]
Ah, thanks.
